mode: rule
proxies:
  - name: VM-0-17-ubuntu-vmess-443
    type: vmess
    server: 43.153.117.54
    port: 443
    uuid: 6bcb015f-13da-46f4-a145-a52c3e99f8fe
    alterId: 0
    cipher: auto
    udp: true
    tls: false
    network: tcp
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - VM-0-17-ubuntu-vmess-443
      - DIRECT
rules:
  - DOMAIN-SUFFIX,local,DIRECT
  - DOMAIN-SUFFIX,localhost,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-SUFFIX,xiaohongshu.com,DIRECT
  - DOMAIN-SUFFIX,weclawai.cc,DIRECT
  - DOMAIN-SUFFIX,npmmirror.com,DIRECT
  - DOMAIN-SUFFIX,taobao.org,DIRECT
  - DOMAIN-SUFFIX,aliyun.com,DIRECT
  - DOMAIN-SUFFIX,tencent.com,DIRECT
  - DOMAIN-SUFFIX,ip-api.com,DIRECT
  - DOMAIN-SUFFIX,ipip.net,DIRECT
  - DOMAIN-SUFFIX,ip138.com,DIRECT
  - DOMAIN-SUFFIX,skype.com,DIRECT
  - DOMAIN-SUFFIX,skype.comedge.skype.net,DIRECT
  - DOMAIN-SUFFIX,skypeassets.com,DIRECT
  - DOMAIN-SUFFIX,skypeforbusiness.com,DIRECT
  - DOMAIN-SUFFIX,cdnkuaisou.com,DIRECT
  - DOMAIN-SUFFIX,cnkuaishou.com,DIRECT
  - DOMAIN-SUFFIX,cdnkuaishou.com,DIRECT
  - DOMAIN-SUFFIX,cmhuawei.com,DIRECT
  - DOMAIN-SUFFIX,cdnhuawei.com,DIRECT
  - DOMAIN-SUFFIX,viphuawei.com,DIRECT
  - DOMAIN-SUFFIX,chromeapi.com,DIRECT
  - DOMAIN-SUFFIX,paypal.com,DIRECT
  - DOMAIN-SUFFIX,alipay.com,DIRECT
  - DOMAIN-SUFFIX,airwallex.com,DIRECT
  - DOMAIN-SUFFIX,stripe.com,DIRECT
  - DOMAIN-SUFFIX,wooshpay.com,DIRECT
  - DOMAIN-SUFFIX,payssion.com,DIRECT
  - DOMAIN-SUFFIX,chrapi.com,DIRECT
  - DOMAIN-SUFFIX,firapi.com,DIRECT
  - DOMAIN-SUFFIX,gheapi.com,DIRECT
  - DOMAIN-SUFFIX,broapi.com,DIRECT
  - DOMAIN-SUFFIX,edgapi.com,DIRECT
  - DOMAIN-SUFFIX,browserapi.net,DIRECT
  - DOMAIN-SUFFIX,cnsync.com,DIRECT
  - DOMAIN-SUFFIX,on1t.com,DIRECT
  - DOMAIN-SUFFIX,chromeapi.net,DIRECT
  - DOMAIN-SUFFIX,copydesign.net,DIRECT
  - DOMAIN-SUFFIX,jy3p.com,DIRECT
  - DOMAIN-SUFFIX,p5pv.com,DIRECT
  - DOMAIN-SUFFIX,z7zi.com,DIRECT
  - DOMAIN-SUFFIX,j2ai.com,DIRECT
  - DOMAIN-SUFFIX,alrihla.net,DIRECT
  - DOMAIN-SUFFIX,sphinxsearch.net,DIRECT
  - DOMAIN-KEYWORD,google,Proxy
  - DOMAIN-KEYWORD,youtube,Proxy
  - DOMAIN-SUFFIX,ggpht.com,Proxy
  - DOMAIN-SUFFIX,gmail.com,Proxy
  - DOMAIN-SUFFIX,gvt2.com,Proxy
  - DOMAIN-SUFFIX,gvt3.com,Proxy
  - DOMAIN-SUFFIX,chrome.com,Proxy
  - DOMAIN-SUFFIX,wikipedia.org,Proxy
  - DOMAIN-SUFFIX,wikimedia.org,Proxy
  - DOMAIN-SUFFIX,appspot.com,Proxy
  - DOMAIN-SUFFIX,android.com,Proxy
  - DOMAIN-SUFFIX,github.com,Proxy
  - DOMAIN-SUFFIX,gitbook.com,Proxy
  - DOMAIN-SUFFIX,kaggle.com,Proxy
  - DOMAIN-SUFFIX,arxiv.org,Proxy
  - DOMAIN-SUFFIX,wiktionary.org,Proxy
  - DOMAIN-SUFFIX,blogger.com,Proxy
  - DOMAIN-SUFFIX,youtu.be,Proxy
  - DOMAIN-SUFFIX,ytimg.com,Proxy
  - DOMAIN-SUFFIX,youtube.com,Proxy
  - DOMAIN-SUFFIX,instagram.com,Proxy
  - DOMAIN-SUFFIX,twitter.com,Proxy
  - DOMAIN-SUFFIX,t.co,Proxy
  - DOMAIN-SUFFIX,facebook.com,Proxy
  - DOMAIN-SUFFIX,telegram.org,Proxy
  - DOMAIN-SUFFIX,whatsapp.com,Proxy
  - DOMAIN-SUFFIX,whatsapp.net,Proxy
  - DOMAIN-SUFFIX,linkedin.com,Proxy
  - DOMAIN-SUFFIX,licdn.com,Proxy
  - DOMAIN-SUFFIX,trkn.us,Proxy
  - DOMAIN-SUFFIX,cedexis.com,Proxy
  - DOMAIN-SUFFIX,ip.sb,Proxy
  - DOMAIN-SUFFIX,ip.net,Proxy
  - DOMAIN-SUFFIX,openai.com,Proxy
  - DOMAIN-SUFFIX,auth0.com,Proxy
  - DOMAIN-SUFFIX,featuregates.org,Proxy
  - DOMAIN-SUFFIX,statsigapi.net,Proxy
  - DOMAIN-SUFFIX,intercom.io,Proxy
  - DOMAIN-SUFFIX,intercomcdn.com,Proxy
  - DOMAIN-SUFFIX,sentry.io,Proxy
  - DOMAIN-SUFFIX,sentry.dev,Proxy
  - DOMAIN-SUFFIX,oaistatic.com,Proxy
  - DOMAIN-SUFFIX,oaiusercontent.com,Proxy
  - DOMAIN-SUFFIX,chatgpt.com,Proxy
  - DOMAIN-SUFFIX,chatgpt-async-webps-prod-southcentralus-6.webpubsub.azure.com,Proxy
  - DOMAIN-SUFFIX,claude.ai,Proxy
  - DOMAIN-SUFFIX,anthropic.com,Proxy
  - DOMAIN-SUFFIX,bing.com,Proxy
  - DOMAIN-SUFFIX,microsoftonline.com,Proxy
  - DOMAIN-SUFFIX,live.com,Proxy
  - DOMAIN-SUFFIX,msecnd.net,Proxy
  - DOMAIN-SUFFIX,msn.com,Proxy
  - DOMAIN-SUFFIX,bingapis.com,Proxy
  - DOMAIN-SUFFIX,bing.net,Proxy
  - DOMAIN-SUFFIX,windows.com,Proxy
  - DOMAIN-SUFFIX,microsoft.com,Proxy
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
